### ISSUE TITLE
jtgng releases broken after 99a6fb4

### ISSUE THREAD

**Issue by Sheeg** [mattpannella/jtmirror#5]
As per title, I installed the latest version of jtgng, adff9d5 via Pocket_Updater, and when attempted to run it gives "Error in Framework, Bitstream load failed". I had to go back to version 99a6fb4 before I could get it to launch. This is on a fresh SD card on a brand new Pocket. Not sure if this is an issue with these packaged releases, or with the core itself, but thought you ought to know that the releases hosted here appear to be broken after that point.

**Comment by mattpannella** [comment]
just took a quick look and it looks like the issue is the core.json file in the gng core is pointing at the wrong file. I think double dragon 2? 

https://github.com/jotego/jtbin/tree/master/pocket/raw/Cores/jotego.jtgng

**Comment by mattpannella** [comment]
I submitted a PR to jotegos repo to fix it

**Comment by Sheeg** [comment]
Awesome, that's definitely fixed it!
